cleanups and sync upstream while fixing GCC-11 warnings

diff --git a/script/AllRunImageParSaveMemory b/script/AllRunImageParSaveMemory
--- a/script/AllRunImageParSaveMemory
+++ b/script/AllRunImageParSaveMemory
@@ -9,15 +9,15 @@ usage()
 	echo "  arg1: name of images to run flow simulations on (defaults is *.mhd)"
 	echo "  arg2: flow direction(s):  any combination of X Y Z"
 	echo "  arg3: output format for FOAM2Voxel: \".dat\", \".raw\" , \".tif\" (default), "
-	echo "        or \"oldAscii\" (for compatibility with old IC codes)" 
-	echo "Example:" 
-	echo "$scriptName \"\$(ls *.mhd)\"" 
+	echo "        or \"oldAscii\" (for compatibility with old IC codes)"
+	echo "Example:"
+	echo "$scriptName \"\$(ls *.mhd)\""
 }
 if [ "$1" == "" ]; then usage; fi
 if [ "$1" == "-h" ]; then usage; exit; fi
 if [ "$1" == "--help" ]; then usage; exit; fi
-if [ -n "$2" ] ; then 
-	if [[ $2 != [XYZ] ]]; then echo "Error: \$2 ($2) can be X Y or Z only ";  exit; fi 
+if [ -n "$2" ] ; then
+	if [[ $2 != [XYZ] ]]; then echo "Error: \$2 ($2) can be X Y or Z only ";  exit; fi
 fi
 echo $scriptName $@
 echo
@@ -36,7 +36,7 @@ baseCase="base"
 myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
 : ${msSrc:=$myCurrentDIR} ; export msSrc
 
-#dataFiles="Berea.mhd" 
+#dataFiles="Berea.mhd"
 if [ -n "$1" ]; then  dataFiles=$1
 else                  dataFiles="$(ls *.mhd)"
 fi
@@ -79,13 +79,13 @@ do
 echo "p @ $direction : $p  Pa"
 
   caseName="$prefix""$dataFile-$p""-$direction"
-  if  ! [ -d $caseName ]; then 
+  if  ! [ -d $caseName ]; then
 	#~ LAM_MPI_SESSION_SUFFIX="$(echo $caseName | sed 's/\///g')"
 	#~ echo $LAM_MPI_SESSION_SUFFIX
-	#~ lamboot -v machines.txt 
+	#~ lamboot -v machines.txt
 
-	if  ! [ -f $dataFile.mhd ]; then 
-	 if   [ -f $dataFile.nhdr ]; then 
+	if  ! [ -f $dataFile.mhd ]; then
+	 if   [ -f $dataFile.nhdr ]; then
 	  echo "ObjectType =  Image" >  $dataFile.mhd
 	  echo "NDims =       3"     >>  $dataFile.mhd
 	  echo "ElementType = MET_UCHAR"  >>  $dataFile.mhd
@@ -93,7 +93,7 @@ echo "p @ $direction : $p  Pa"
 	  tmpp=`more $dataFile.nhdr | grep sizes |  sed 's/sizes/ /'  |  sed 's/:/ /'`
 	  echo $tmpp
 	  echo "DimSize =  $tmpp" >>  $dataFile.mhd
-	  tmpp=$(more $dataFile.nhdr | grep directions |  sed 's/directions/ /' |  sed 's/space//'  |  sed 's/:/ /') 
+	  tmpp=$(more $dataFile.nhdr | grep directions |  sed 's/directions/ /' |  sed 's/space//'  |  sed 's/:/ /')
 	  echo $tmpp
 	  echo  >>  $dataFile.mhd
 	  echo "ElementSize =  $tmpp" | sed 's/\,/ /g' | sed 's/)/ /g' | sed 's/(/ /g' | sed 's/ 0 / /g' | sed 's/ 0 / /g' >>  $dataFile.mhd
@@ -129,7 +129,7 @@ echo "p @ $direction : $p  Pa"
 	nlProc=`cd $caseName && ls -d -1 processo*[0-9] 2>/dev/null | sed 's/processor//g' | sort -n -r | head -n 1`
 	nProc=$[nlProc+1]
 	echo nProc $nProc
-	setKeywordValues numberOfSubdomains $nProc ./$caseName/system/decomposeParDict 
+	setKeywordValues numberOfSubdomains $nProc ./$caseName/system/decomposeParDict
 
 
 
@@ -137,30 +137,30 @@ echo "p @ $direction : $p  Pa"
 
 
 
-	setBoundaryCondition "$direction"  "value" "uniform  $p" ./$caseName/0/p 
+	setBoundaryCondition "$direction"  "value" "uniform  $p" ./$caseName/0/p
 
 
 	#(cd $caseName && runMPI redistributePar $nProc -overwrite)
 	(cd $caseName && runMPI renumberMesh $nProc -overwrite)
 
 
-	setKeywordValues endTime $endTime ./$caseName/system/controlDict 
+	setKeywordValues endTime $endTime ./$caseName/system/controlDict
 
-	#setKeywordValues writeFormat ascii ./$caseName/system/controlDict 
+	#setKeywordValues writeFormat ascii ./$caseName/system/controlDict
 
 	(cd $caseName && runMPI iPotentialFoam $nProc)
 
-	#setKeywordValues writeFormat binary ./$caseName/system/controlDict 
+	#setKeywordValues writeFormat binary ./$caseName/system/controlDict
 
 	setSubKeywordValues relaxationFactors "U" "0.5" ./$caseName/system/fvSolution
 
-	setKeywordValues writeInterval 1000 ./$caseName/system/controlDict 
+	setKeywordValues writeInterval 1000 ./$caseName/system/controlDict
 	echo "..................Running single phase flow code......................."
 	(cd $caseName && runMPI icoNSFoam $nProc)
 	(cd $caseName && mv log.icoNSFoam log.icoNSFoam.1)
 
 	#setSubKeywordValues relaxationFactors "U" "0.4" ./$caseName/system/fvSolution
-	#setKeywordValues writeInterval 100 ./$caseName/system/controlDict 
+	#setKeywordValues writeInterval 100 ./$caseName/system/controlDict
 	#(cd $caseName && runMPI icoNSFoam $nProc)
 	#(cd $caseName && mv log.icoNSFoam log.icoNSFoam.2)
 
@@ -181,7 +181,3 @@ echo "p @ $direction : $p  Pa"
 done
 done
 done
-
-
-
-
